// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;
using CoreGraphics;
using System.Text; 

namespace DataManip
{

	public partial class LocationViewController : UIViewController
	{
		public string strSampleString { get;set;} 
		LocationPredictionClass objAutoCompleteLocationClass;
		string strAutoCompleteQuery;
		LocationAutoCompleteTableSource objLocationAutoCompleteTableSource;
		public LocationViewController (IntPtr handle) : base (handle)
		{
			
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();  
			FnInitializeView();
			FnClickEventInit ();
		}

		void FnInitializeView()
		{  
			tableViewLocationAutoComplete.Hidden = true; 
			txtLocation.ShouldReturn  += (textField) => textField.ResignFirstResponder();  

			StringBuilder builderLocationAutoComplete = new StringBuilder (Constants.strPlacesAutofillUrl);
			builderLocationAutoComplete.Append ("?input={0}").Append("&key=").Append(Constants.strGooglePlaceAPILey);
			strAutoCompleteQuery = builderLocationAutoComplete.ToString ();
			builderLocationAutoComplete.Clear ();
			builderLocationAutoComplete = null;

		}
		void FnClickEventInit()
		{
			txtLocation.EditingChanged+=async delegate(object sender , EventArgs e )
			{
				if(string.IsNullOrWhiteSpace(txtLocation.Text))
				{
					tableViewLocationAutoComplete.Hidden =true;
				}
				else
				{
					if(txtLocation.Text.Length >3)
					{ 

						//Autofill
						string strFullURL = string.Format (strAutoCompleteQuery,txtLocation.Text);
						objAutoCompleteLocationClass= await RestRequestClass.LocationAutoComplete (strFullURL);
 

						if(objAutoCompleteLocationClass!=null && objAutoCompleteLocationClass.status=="OK")
						{
							if ( objAutoCompleteLocationClass.predictions.Count > 0 )
							{
								if(objLocationAutoCompleteTableSource!=null)
								{
									objLocationAutoCompleteTableSource.LocationRowSelectedEventAction -= LocationSelectedFromAutoFill;
									objLocationAutoCompleteTableSource=null;
								}

								tableViewLocationAutoComplete.Hidden = false;
								objLocationAutoCompleteTableSource = new LocationAutoCompleteTableSource ( objAutoCompleteLocationClass.predictions );
								objLocationAutoCompleteTableSource.LocationRowSelectedEventAction += LocationSelectedFromAutoFill;
								tableViewLocationAutoComplete.Source = objLocationAutoCompleteTableSource;
								tableViewLocationAutoComplete.ReloadData ();
							}
							else
								tableViewLocationAutoComplete.Hidden = true;
						}
						else
						{
							tableViewLocationAutoComplete.Hidden=true;
						} 
					}
				}
			};
		
			btnBack.TouchUpInside+= delegate(object sender , EventArgs e )
			{
				DismissViewController(true,null);
			};
		}

		void LocationSelectedFromAutoFill(Prediction objPrediction)
		{
			Console.WriteLine ( objPrediction.description );
			txtLocation.ResignFirstResponder ();
		}
	}
}
